[workspace]
members = [
    "chirp-sys"
, "chirp-wrapper"]
[package]
name = "chirp"
version = "0.1.0"
edition = "2021"

[dependencies]
chirp-sys = { path = "chirp-sys" }
autocxx = "0.27.0"
cxx = "1.0.124"

[build-dependencies]
autocxx-build = "0.27.0"
