[workspace]
members = [
    "chirp-rt",
    "chirp-rt/macros",
    "chirp-sys",
    "chirpc",
    "chirp-wrapper"
]
[package]
name = "chirp"
version = "0.1.0"
edition = "2021"

[dependencies]
chirp-sys = { path = "chirp-sys" }
chirp-wrapper = {path = "chirp-wrapper"}
